In [93]:
import pandas as pd
import numpy as np
import seaborn as sns
import datetime as dt

In [94]:
df = pd.read_csv(r"C:\Users\DELL\Documents\youtube_likes project\USvideos.csv")

In [95]:
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John..."
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,BZt0qjTWNhw,18.14.06,The Cat Who Caught the Laser,AaronsAnimals,15,2018-05-18T13:00:04.000Z,"aarons animals|""aarons""|""animals""|""cat""|""cats""...",1685609,38160,1385,2657,https://i.ytimg.com/vi/BZt0qjTWNhw/default.jpg,False,False,False,The Cat Who Caught the Laser - Aaron's Animals
40945,1h7KV2sjUWY,18.14.06,True Facts : Ant Mutualism,zefrank1,22,2018-05-18T01:00:06.000Z,[none],1064798,60008,382,3936,https://i.ytimg.com/vi/1h7KV2sjUWY/default.jpg,False,False,False,NaN
40946,D6Oy4LfoqsU,18.14.06,I GAVE SAFIYA NYGAARD A PERFECT HAIR MAKEOVER ...,Brad Mondo,24,2018-05-18T17:34:22.000Z,I gave safiya nygaard a perfect hair makeover ...,1066451,48068,1032,3992,https://i.ytimg.com/vi/D6Oy4LfoqsU/default.jpg,False,False,False,I had so much fun transforming Safiyas hair in...
40947,oV0zkMe1K8s,18.14.06,How Black Panther Should Have Ended,How It Should Have Ended,1,2018-05-17T17:00:04.000Z,"Black Panther|""HISHE""|""Marvel""|""Infinity War""|...",5660813,192957,2846,13088,https://i.ytimg.com/vi/oV0zkMe1K8s/default.jpg,False,False,False,How Black Panther Should Have EndedWatch More ...
40948,ooyjaVdt-jA,18.14.06,Official Call of Duty®: Black Ops 4 — Multipla...,Call of Duty,20,2018-05-17T17:09:38.000Z,"call of duty|""cod""|""activision""|""Black Ops 4""",10306119,357079,212976,144795,https://i.ytimg.com/vi/ooyjaVdt-jA/default.jpg,False,False,False,Call of Duty: Black Ops 4 Multiplayer raises t...

In [96]:
df2 = pd.read_json(r"C:\Users\DELL\Documents\youtube_likes project\US_category_id.json")

In [97]:
df2

,kind,etag,items
0,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
1,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
2,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
3,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
4,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
5,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
6,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
7,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
8,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
9,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
10,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
11,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
12,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
13,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
14,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
15,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
16,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
17,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
18,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
19,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
20,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
21,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
22,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
23,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
24,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
25,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
26,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
27,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
28,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
29,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
30,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."
31,youtube#videoCategoryListResponse,"""m2yskBQFythfE4irbTIeOgYYfBU/S730Ilt-Fi-emsQJv...","{'kind': 'youtube#videoCategory', 'etag': '""m2..."

In [98]:
df.drop(['description','thumbnail_link','tags'],axis=1,inplace=True)

In [99]:
df['publish_time'] = pd.to_datetime(df['publish_time'])

In [100]:
df['trending_date'] = pd.to_datetime(df['trending_date'],format='%y.%d.%m')

In [101]:
df['publish_year'] = df['publish_time'].dt.year

In [102]:
df['publish_month'] = df['publish_time'].dt.month_name()

In [103]:
title = [df2['items'][i]['snippet']['title'] for i in range(0,32)]

In [104]:
id = [df2['items'][i]['id'] for i in range(0,32)]

In [105]:
id_genre = pd.DataFrame({'category_id':id,'genre':title})

In [106]:
id_genre['category_id'] = id_genre['category_id'].astype(int)

In [107]:
id_genre

    category_id                  genre
0             1       Film & Animation
1             2       Autos & Vehicles
2            10                  Music
3            15         Pets & Animals
4            17                 Sports
5            18           Short Movies
6            19        Travel & Events
7            20                 Gaming
8            21          Videoblogging
9            22         People & Blogs
10           23                 Comedy
11           24          Entertainment
12           25        News & Politics
13           26          Howto & Style
14           27              Education
15           28   Science & Technology
16           29  Nonprofits & Activism
17           30                 Movies
18           31        Anime/Animation
19           32       Action/Adventure
20           33               Classics
21           34                 Comedy
22           35            Documentary
23           36                  Drama
24           37                 Family
25           38                Foreign
26           39                 Horror
27           40         Sci-Fi/Fantasy
28           41               Thriller
29           42                 Shorts
30           43                  Shows
31           44               Trailers

In [108]:
df = pd.merge(df,id_genre,how='inner',on='category_id')

In [109]:
df

,video_id,trending_date,title,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,publish_year,publish_month,genre
0,2kyS6SvSYSE,2017-11-14,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13 17:13:01+00:00,748374,57527,2966,15954,False,False,False,2017,November,People & Blogs
1,0mlNzVSJrT0,2017-11-14,Me-O Cats Commercial,Nobrand,22,2017-04-21 06:47:32+00:00,98966,2486,184,532,False,False,False,2017,April,People & Blogs
2,STI2fI7sKMo,2017-11-14,"AFFAIRS, EX BOYFRIENDS, $18MILLION NET WORTH -...",Shawn Johnson East,22,2017-11-11 15:00:03+00:00,321053,4451,1772,895,False,False,False,2017,November,People & Blogs
3,KODzih-pYlU,2017-11-14,BLIND(folded) CAKE DECORATING CONTEST (with Mo...,Grace Helbig,22,2017-11-11 18:08:04+00:00,197062,7250,217,456,False,False,False,2017,November,People & Blogs
4,8mhTWqWlQzU,2017-11-14,Wearing Online Dollar Store Makeup For A Week,Safiya Nygaard,22,2017-11-11 01:19:33+00:00,2744430,115426,1110,6541,False,False,False,2017,November,People & Blogs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,V6ElE2xs48c,2018-06-02,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,1324482,22413,608,1644,False,False,False,2018,May,Shows
40945,V6ElE2xs48c,2018-06-03,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,1332252,22461,610,1648,False,False,False,2018,May,Shows
40946,V6ElE2xs48c,2018-06-04,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,1340039,22504,615,1648,False,False,False,2018,May,Shows
40947,V6ElE2xs48c,2018-06-05,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,1345086,22542,615,1649,False,False,False,2018,May,Shows
40948,V6ElE2xs48c,2018-06-06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,43,2018-05-10 21:01:22+00:00,1351321,22587,616,1649,False,False,False,2018,May,Shows

In [110]:
df = df.loc[:,['video_id','publish_time','publish_year', 'publish_month', 'trending_date', 'title', 'channel_title', 'views', 'likes', 'dislikes', 'comment_count',
       'comments_disabled', 'ratings_disabled', 'video_error_or_removed','category_id', 'genre']]

In [111]:
df.head(3)

,video_id,publish_time,publish_year,publish_month,trending_date,title,channel_title,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,category_id,genre
0,2kyS6SvSYSE,2017-11-13 17:13:01+00:00,2017,November,2017-11-14,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,748374,57527,2966,15954,False,False,False,22,People & Blogs
1,0mlNzVSJrT0,2017-04-21 06:47:32+00:00,2017,April,2017-11-14,Me-O Cats Commercial,Nobrand,98966,2486,184,532,False,False,False,22,People & Blogs
2,STI2fI7sKMo,2017-11-11 15:00:03+00:00,2017,November,2017-11-14,"AFFAIRS, EX BOYFRIENDS, $18MILLION NET WORTH -...",Shawn Johnson East,321053,4451,1772,895,False,False,False,22,People & Blogs

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40949 entries, 0 to 40948
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40949 non-null  object
 1   publish_time            40949 non-null  datetime64[ns, UTC]
 2   publish_year            40949 non-null  int32
 3   publish_month           40949 non-null  object
 4   trending_date           40949 non-null  datetime64[ns]
 5   title                   40949 non-null  object
 6   channel_title           40949 non-null  object
 7   views                   40949 non-null  int64
 8   likes                   40949 non-null  int64
 9   dislikes                40949 non-null  int64
 10  comment_count           40949 non-null  int64
 11  comments_disabled       40949 non-null  bool
 12  ratings_disabled        40949 non-null  bool
 13  video_error_or_removed  40949 non-null  bool
 14  category_id             40949 non-null  int64
 15  genre                   40949 non-null  object
dtypes: bool(3), datetime64[ns, UTC](1), datetime64[ns](1), int32(1), int64(5), object(5)
memory usage: 4.0+ MB

In [113]:
df['publish_time'] = df['publish_time'].astype(str)

In [114]:
#string slicing in dataframes
df['publish_time'] = df['publish_time'].str[:10]

In [115]:
df = df.loc[:,['video_id','publish_time','publish_year', 'publish_month', 'trending_date', 'title', 'channel_title', 'views', 'likes', 'dislikes', 'comment_count',
       'comments_disabled', 'ratings_disabled', 'video_error_or_removed','category_id', 'genre']]

In [116]:
df

,video_id,publish_time,publish_year,publish_month,trending_date,title,channel_title,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled,video_error_or_removed,category_id,genre
0,2kyS6SvSYSE,2017-11-13,2017,November,2017-11-14,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,748374,57527,2966,15954,False,False,False,22,People & Blogs
1,0mlNzVSJrT0,2017-04-21,2017,April,2017-11-14,Me-O Cats Commercial,Nobrand,98966,2486,184,532,False,False,False,22,People & Blogs
2,STI2fI7sKMo,2017-11-11,2017,November,2017-11-14,"AFFAIRS, EX BOYFRIENDS, $18MILLION NET WORTH -...",Shawn Johnson East,321053,4451,1772,895,False,False,False,22,People & Blogs
3,KODzih-pYlU,2017-11-11,2017,November,2017-11-14,BLIND(folded) CAKE DECORATING CONTEST (with Mo...,Grace Helbig,197062,7250,217,456,False,False,False,22,People & Blogs
4,8mhTWqWlQzU,2017-11-11,2017,November,2017-11-14,Wearing Online Dollar Store Makeup For A Week,Safiya Nygaard,2744430,115426,1110,6541,False,False,False,22,People & Blogs
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40944,V6ElE2xs48c,2018-05-10,2018,May,2018-06-02,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,1324482,22413,608,1644,False,False,False,43,Shows
40945,V6ElE2xs48c,2018-05-10,2018,May,2018-06-03,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,1332252,22461,610,1648,False,False,False,43,Shows
40946,V6ElE2xs48c,2018-05-10,2018,May,2018-06-04,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,1340039,22504,615,1648,False,False,False,43,Shows
40947,V6ElE2xs48c,2018-05-10,2018,May,2018-06-05,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,1345086,22542,615,1649,False,False,False,43,Shows
40948,V6ElE2xs48c,2018-05-10,2018,May,2018-06-06,Game of Zones - S5:E5: The Isle of Van Gundy,Bleacher Report,1351321,22587,616,1649,False,False,False,43,Shows

In [117]:
df['genre'].unique()

array(['People & Blogs', 'Entertainment', 'Comedy',
       'Science & Technology', 'Film & Animation', 'News & Politics',
       'Sports', 'Music', 'Pets & Animals', 'Education', 'Howto & Style',
       'Autos & Vehicles', 'Travel & Events', 'Gaming',
       'Nonprofits & Activism', 'Shows'], dtype=object)

In [118]:
music = df.loc[(df['genre']=='Music')&(df['channel_title'].str.contains('childish',case=False))&(df['title'].str.contains('this is america',case=False)),['channel_title','title','genre','publish_month','publish_year','publish_time','trending_date','views']]

In [119]:
entertainment = df.loc[(df['genre']=='Entertainment')&(df['channel_title'].str.contains('the graham norton',case=False))&(df['title'].str.contains('jason momoa shows off',case=False)),['channel_title','title','genre','publish_month','publish_year','trending_date','views']]

In [120]:
nonprof = df.loc[(df['genre']=='Nonprofits & Activism')&(df['channel_title'].str.contains('logan paul vlogs',case=False))&(df['title'].str.contains('suicide:',case=False)),['channel_title','title','genre','publish_month','publish_year','trending_date','views']]

In [121]:
music.head()

,channel_title,title,genre,publish_month,publish_year,publish_time,trending_date,views
30920,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-08,31648454
30957,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-09,47169016
30998,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-10,60776509
31038,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-11,73432600
31084,ChildishGambinoVEVO,Childish Gambino - This Is America (Official V...,Music,May,2018,2018-05-06,2018-05-12,85092067

In [122]:
entertainment

,channel_title,title,genre,publish_month,publish_year,trending_date,views
3256,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-15,391049
3310,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-16,574778
3368,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-17,647820
3420,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-18,694375
3473,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-19,732349
3529,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-20,766050
3581,The Graham Norton Show,Jason Momoa Shows Off His Aquaman Quindent | T...,Entertainment,November,2017,2017-11-21,792184

In [123]:
nonprof

,channel_title,title,genre,publish_month,publish_year,trending_date,views
40858,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-25,8041970
40859,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-26,15808339
40860,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-27,19092511
40861,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-28,21104436
40862,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-29,22387656
40863,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-30,23164093
40864,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-01-31,23742391
40865,Logan Paul Vlogs,Suicide: Be Here Tomorrow.,Nonprofits & Activism,January,2018,2018-02-01,24286474

In [124]:
df.loc[(df['genre']=='Music'),['video_id','channel_title','title','genre','publish_time','publish_month','publish_year','trending_date','views']]

,video_id,channel_title,title,genre,publish_time,publish_month,publish_year,trending_date,views
26038,5E4ZBSInqUU,marshmello,Marshmello - Blocks (Official Music Video),Music,2017-11-13,November,2017,2017-11-14,687582
26039,n1WpP7iowLc,EminemVEVO,Eminem - Walk On Water (Audio) ft. Beyoncé,Music,2017-11-10,November,2017,2017-11-14,17158531
26040,e_7zHm7GsYc,Hunter Hayes,Hunter Hayes - You Should Be Loved (Part One O...,Music,2017-11-13,November,2017,2017-11-14,13917
26041,zZ9FciUx6gs,Nickelback,Nickelback - The Betrayal Act III [Official Vi...,Music,2017-11-13,November,2017,2017-11-14,57169
26042,PaJCFHXcWmM,U2VEVO,U2 - The Blackout,Music,2017-11-13,November,2017,2017-11-14,60506
...,...,...,...,...,...,...,...,...,...
32505,2in8XqiElwc,NickiMinajAtVEVO,Nicki Minaj - Chun-Li (Live on SNL / 2018),Music,2018-05-20,May,2018,2018-06-14,4945185
32506,n_W54baizX8,Daddy Yankee,Daddy Yankee - Hielo (Video Oficial),Music,2018-05-18,May,2018,2018-06-14,41803845
32507,pcJo0tIWybY,SZAVEVO,SZA - Garden (Say It Like Dat) (Official Video),Music,2018-05-18,May,2018,2018-06-14,6004782
32508,7UoP9ABJXGE,Dan And Shay,Dan + Shay - Speechless (Wedding Video),Music,2018-05-18,May,2018,2018-06-14,5534278
32509,ju_inUnrLc4,FifthHarmonyVEVO,Fifth Harmony - Don't Say You Love Me,Music,2018-05-18,May,2018,2018-06-14,23502572

In [125]:
df['trending_date']=pd.to_datetime(df['trending_date'])

In [126]:
df['publish_time']=pd.to_datetime(df['publish_time'])

In [127]:
df.dtypes

video_id                          object
publish_time              datetime64[ns]
publish_year                       int32
publish_month                     object
trending_date             datetime64[ns]
title                             object
channel_title                     object
views                              int64
likes                              int64
dislikes                           int64
comment_count                      int64
comments_disabled                   bool
ratings_disabled                    bool
video_error_or_removed              bool
category_id                        int64
genre                             object
dtype: object

Days to Trendings

In [128]:
df['days_to_trend'] = (df['trending_date'] - df['publish_time']).dt.days

In [129]:
music_df = df[df['genre'] == 'Music']

In [130]:
first_5_days_df = music_df[music_df['days_to_trend'] <= 5]

In [131]:
first_5_days_views = first_5_days_df.groupby('video_id')['views'].mean()

In [132]:
first_5_days_views

video_id
-2aVkGcI7ZA     1668643.5
-35jibKqbEo     1082718.2
-5aaJJQFvOg      562232.0
-9rdDeWzvsU      296615.0
-BDImdAfodA      770754.5
                  ...
zi_6oaQyckM     4478349.8
zkG4Xpz6t68    14852405.2
zkrq7Kpd1so     1648886.0
zvjqcoiOPbE      672352.5
zwEn-ambXLw      127245.0
Name: views, Length: 765, dtype: float64